# Database configuration
spring:
 datasource:
  url: jdbc:h2:mem:georeferenciamentodb
  username: sa
  password:
 h2:
  console:
   enabled: true
   path: /h2-console

api:
 ibge:
  url: https://servicodados.ibge.gov.br/api
